  import pkg from "pg";
  import dotenv from "dotenv";
  import path from "path";
  import { fileURLToPath } from "url";

  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  dotenv.config({ path: path.resolve(__dirname, "../.env") });

  const { Pool } = pkg;

  const pool = new Pool({
    user: String(process.env.PGUSER),
    host: String(process.env.PGHOST),
    database: String(process.env.PGDATABASE),
    password: String(process.env.PGPASSWORD),
    port: Number(process.env.PGPORT),
  });

  const sampleRecipes = [
    {
      recipe_name: "Spaghetti Carbonara",
      category: "Italian",
      ingredients: "Spaghetti, eggs, pancetta, Parmesan cheese, black pepper, olive oil, salt",
      instructions: "Cook spaghetti until al dente. In a pan, fry pancetta until crisp. Beat eggs with Parmesan and pepper. Combine hot pasta with pancetta and remove from heat. Quickly stir in egg mixture until creamy. Serve immediately with extra cheese.",
      image_url: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    },
    {
      recipe_name: "Butter Chicken",
      category: "Indian",
      ingredients: "Chicken, tomato puree, butter, cream, garam masala, ginger, garlic, chili powder, cumin",
      instructions: "Marinate chicken in yogurt and spices, then grill or sauté until golden. In a pan, melt butter, add ginger-garlic paste, tomato puree, and spices. Simmer with cream until thickened. Add chicken and cook until flavors blend. Serve with naan or rice.",
      image_url: "https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg",
    },
    {
      recipe_name: "Beef Stroganoff",
      category: "Russian",
      ingredients: "Beef strips, mushrooms, onion, sour cream, Dijon mustard, beef stock, butter, flour",
      instructions: "Sauté onions and mushrooms in butter. Add beef and cook until browned. Stir in flour, then pour in beef stock. Simmer until thickened. Mix in sour cream and mustard just before serving. Serve over egg noodles or mashed potatoes.",
      image_url: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    },
    {
      recipe_name: "Vegetable Fried Rice",
      category: "Asian",
      ingredients: "Rice, carrots, peas, spring onions, soy sauce, sesame oil, eggs, garlic, ginger",
      instructions: "Cook rice and let cool. Scramble eggs and set aside. Stir fry garlic, ginger, and veggies in sesame oil. Add rice, soy sauce, and mix well. Add eggs back in and toss everything evenly. Serve hot with spring onions.",
      image_url: "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    },
    {
      recipe_name: "Fish Tacos",
      category: "Mexican",
      ingredients: "White fish, tortillas, cabbage, lime, sour cream, cilantro, chili powder, garlic powder",
      instructions: "Season fish with chili and garlic powder, grill until flaky. In a bowl, mix sour cream, lime juice, and cilantro for sauce. Fill tortillas with cabbage, grilled fish, and drizzle with sauce. Serve with lime wedges.",
      image_url: "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
    },
    {
      recipe_name: "Classic Cheeseburger",
      category: "American",
      ingredients: "Ground beef, burger buns, cheddar cheese, lettuce, tomato, onion, ketchup, mustard",
      instructions: "Form beef patties and season with salt and pepper. Grill until medium-rare or well-done. Add cheese to melt. Assemble buns with lettuce, tomato, onions, patty, and sauces. Serve with fries or coleslaw.",
      image_url: "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    },
    {
      recipe_name: "Pad Thai",
      category: "Thai",
      ingredients: "Rice noodles, shrimp, tofu, eggs, bean sprouts, peanuts, tamarind paste, fish sauce, sugar",
      instructions: "Soak noodles in warm water. Fry tofu and shrimp, then push aside. Scramble eggs and mix in noodles. Add tamarind sauce mixture and toss until coated. Add bean sprouts and peanuts. Serve with lime and chili flakes.",
      image_url: "https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg",
    },
    {
      recipe_name: "Miso Ramen",
      category: "Japanese",
      ingredients: "Ramen noodles, miso paste, pork broth, soy sauce, garlic, ginger, boiled egg, green onions",
      instructions: "Prepare broth with miso paste, soy sauce, garlic, and ginger. Simmer gently. Cook noodles separately and add to broth. Top with sliced pork, soft-boiled egg, and green onions. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    },
    {
      recipe_name: "Tandoori Chicken",
      category: "Indian",
      ingredients: "Chicken legs, yogurt, lemon juice, garlic, ginger, tandoori masala, chili powder",
      instructions: "Marinate chicken in yogurt, lemon juice, and spices for 4 hours. Grill or bake until cooked and charred. Serve with mint chutney and lemon wedges.",
      image_url: "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    },
    {
      recipe_name: "Greek Salad",
      category: "Greek",
      ingredients: "Cucumber, tomato, red onion, olives, feta cheese, olive oil, oregano, lemon juice",
      instructions: "Chop vegetables into bite-size pieces. Toss with olive oil, lemon juice, oregano, and salt. Add feta and olives on top. Chill before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    },
    {
      recipe_name: "Beef Tacos",
      category: "Mexican",
      ingredients: "Ground beef, taco shells, lettuce, tomato, cheese, taco seasoning, sour cream",
      instructions: "Cook beef with taco seasoning until browned. Fill taco shells with meat, lettuce, tomato, and cheese. Top with sour cream and salsa. Serve immediately.",
      image_url: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    },
    {
      recipe_name: "Margherita Pizza",
      category: "Italian",
      ingredients: "Pizza dough, tomato sauce, mozzarella cheese, basil leaves, olive oil, salt",
      instructions: "Spread tomato sauce on rolled-out dough. Add mozzarella and basil. Drizzle olive oil. Bake in preheated oven at 250°C until crust is golden and cheese melts. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    },
    {
      recipe_name: "Pancakes",
      category: "American",
      ingredients: "Flour, eggs, milk, baking powder, sugar, butter, salt, maple syrup",
      instructions: "Mix dry ingredients, then whisk in milk and eggs. Pour batter on hot greased pan, cook both sides until golden. Serve with butter and syrup.",
      image_url: "https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg",
    },
    {
      recipe_name: "Chicken Caesar Salad",
      category: "Salad",
      ingredients: "Chicken breast, romaine lettuce, croutons, Parmesan cheese, Caesar dressing",
      instructions: "Grill chicken until golden. Chop lettuce, toss with dressing, croutons, and cheese. Add sliced chicken on top. Serve chilled.",
      image_url: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    },
    {
      recipe_name: "Falafel Wrap",
      category: "Middle Eastern",
      ingredients: "Chickpeas, garlic, onion, cumin, coriander, flour, pita bread, tahini sauce",
      instructions: "Blend soaked chickpeas with spices into dough. Form balls and fry until golden. Stuff pita with falafel, veggies, and tahini sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/kd0jen1605299625.jpg",
    },
    {
      recipe_name: "Shrimp Scampi",
      category: "Seafood",
      ingredients: "Shrimp, garlic, butter, lemon juice, parsley, spaghetti, olive oil, chili flakes",
      instructions: "Cook spaghetti. In pan, sauté garlic in butter and olive oil. Add shrimp, cook until pink. Add lemon juice, chili flakes, and toss with pasta. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg",
    },
    {
      recipe_name: "Tom Yum Soup",
      category: "Thai",
      ingredients: "Shrimp, lemongrass, galangal, lime leaves, chili paste, fish sauce, mushrooms, lime juice",
      instructions: "Boil water with lemongrass and galangal. Add shrimp, mushrooms, and chili paste. Season with fish sauce and lime juice. Garnish with cilantro and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    },
    {
      recipe_name: "Ratatouille",
      category: "French",
      ingredients: "Eggplant, zucchini, bell pepper, tomato, onion, garlic, olive oil, herbs de Provence",
      instructions: "Slice all vegetables evenly. Sauté onions and garlic, layer vegetables in pan. Season and bake until tender. Serve warm as a side or main dish.",
      image_url: "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    },
    {
      recipe_name: "Sushi Rolls",
      category: "Japanese",
      ingredients: "Sushi rice, nori sheets, cucumber, avocado, crab sticks, soy sauce, wasabi",
      instructions: "Spread rice on nori, layer fillings, and roll tightly. Slice into pieces using wet knife. Serve with soy sauce and wasabi.",
      image_url: "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
    },
    {
      recipe_name: "Biryani",
      category: "Indian",
      ingredients: "Basmati rice, chicken, onions, yogurt, saffron, spices, ghee, mint, coriander",
      instructions: "Fry onions until golden. Layer half-cooked rice and marinated chicken in pot. Sprinkle saffron milk, cover tightly, and cook on low heat until rice is fluffy. Serve hot with raita.",
      image_url: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    },
    {
      recipe_name: "BBQ Ribs",
      category: "American",
      ingredients: "Pork ribs, BBQ sauce, garlic powder, paprika, salt, brown sugar, vinegar",
      instructions: "Season ribs and bake until tender. Brush with BBQ sauce and grill until caramelized. Serve with coleslaw and fries.",
      image_url: "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    },
    {
      recipe_name: "Caprese Salad",
      category: "Italian",
      ingredients: "Tomatoes, mozzarella cheese, basil, olive oil, balsamic glaze, salt, pepper",
      instructions: "Layer tomato and mozzarella slices alternately. Top with basil leaves, drizzle olive oil and balsamic glaze. Serve fresh.",
      image_url: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    },
    {
      recipe_name: "Chili Con Carne",
      category: "Mexican",
      ingredients: "Ground beef, kidney beans, tomatoes, chili powder, cumin, onions, garlic",
      instructions: "Sauté onions and garlic. Add beef and cook until browned. Stir in spices, beans, and tomatoes. Simmer until thickened. Serve with rice or bread.",
      image_url: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    },
    {
      recipe_name: "Mango Lassi",
      category: "Beverage",
      ingredients: "Ripe mango, yogurt, sugar, cardamom, milk, ice cubes",
      instructions: "Blend mango pieces, yogurt, milk, and sugar until smooth. Add cardamom and ice cubes. Serve chilled.",
      image_url: "https://www.themealdb.com/images/media/drink/tsxpty1468923417.jpg",
    },
    {
      recipe_name: "Chocolate Brownies",
      category: "Dessert",
      ingredients: "Dark chocolate, butter, sugar, eggs, flour, cocoa powder, vanilla extract",
      instructions: "Melt butter and chocolate together. Add sugar and eggs, whisk well. Fold in flour and cocoa. Bake in preheated oven at 180°C for 25 minutes. Cool before cutting.",
      image_url: "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
    },
  {
      recipe_name: "Chicken Alfredo Pasta",
      category: "Italian",
      ingredients: "Fettuccine pasta, chicken breast, butter, garlic, cream, Parmesan cheese, parsley",
      instructions: "Cook pasta until al dente. In a pan, melt butter and sauté garlic. Add cream and Parmesan to make sauce. Add cooked chicken and mix in pasta. Garnish with parsley and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    },
    {
      recipe_name: "Gazpacho",
      category: "Spanish",
      ingredients: "Tomatoes, cucumber, bell pepper, onion, garlic, olive oil, vinegar, bread crumbs",
      instructions: "Blend all ingredients until smooth. Chill for 2 hours before serving. Garnish with chopped vegetables and a drizzle of olive oil.",
      image_url: "https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg",
    },
    {
      recipe_name: "Chicken Shawarma",
      category: "Middle Eastern",
      ingredients: "Chicken thighs, yogurt, lemon juice, garlic, cumin, paprika, pita bread, tahini sauce",
      instructions: "Marinate chicken in yogurt, lemon, and spices overnight. Grill or roast until charred. Slice and wrap in pita with veggies and tahini sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
    },
    {
      recipe_name: "Lemon Tart",
      category: "Dessert",
      ingredients: "Flour, butter, sugar, eggs, lemon juice, lemon zest, cream",
      instructions: "Prepare tart crust and bake. Whisk eggs, sugar, lemon juice, zest, and cream. Pour into crust and bake until set. Cool and serve with powdered sugar.",
      image_url: "https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg",
    },
    {
      recipe_name: "Egg Fried Rice",
      category: "Asian",
      ingredients: "Cooked rice, eggs, peas, carrots, soy sauce, sesame oil, green onions, garlic",
      instructions: "Scramble eggs and set aside. Stir-fry garlic and veggies, then add rice and soy sauce. Mix in eggs and toss well. Garnish with green onions.",
      image_url: "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    },
    {
      recipe_name: "French Onion Soup",
      category: "French",
      ingredients: "Onions, butter, beef stock, thyme, baguette slices, Gruyère cheese, salt, pepper",
      instructions: "Caramelize onions in butter. Add stock and thyme, simmer for 30 minutes. Pour into bowls, top with toasted bread and cheese, broil until golden.",
      image_url: "https://www.themealdb.com/images/media/meals/xvrrux1511784688.jpg",
    },
    {
      recipe_name: "Grilled Cheese Sandwich",
      category: "Snack",
      ingredients: "Bread slices, cheddar cheese, butter",
      instructions: "Butter bread on one side. Place cheese between slices with buttered sides facing out. Grill until golden and cheese melts. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    },
    {
      recipe_name: "Lentil Soup",
      category: "Vegetarian",
      ingredients: "Lentils, carrot, celery, onion, garlic, cumin, olive oil, vegetable stock",
      instructions: "Sauté onions, garlic, and carrots. Add lentils, cumin, and stock. Simmer until lentils are tender. Blend partially and serve with olive oil drizzle.",
      image_url: "https://www.themealdb.com/images/media/meals/vvtvtr1511180578.jpg",
    },
    {
      recipe_name: "Pav Bhaji",
      category: "Indian",
      ingredients: "Potatoes, tomatoes, peas, capsicum, butter, pav bhaji masala, pav buns, onions",
      instructions: "Boil vegetables and mash. In pan, sauté onions and masala, add mashed veggies and butter. Toast pav buns with butter and serve with bhaji and onions.",
      image_url: "https://www.themealdb.com/images/media/meals/tsrtxr1511550407.jpg",
    },
    {
      recipe_name: "Banana Smoothie",
      category: "Beverage",
      ingredients: "Bananas, milk, honey, yogurt, ice cubes",
      instructions: "Blend bananas, milk, honey, and yogurt until smooth. Add ice and blend again. Serve chilled.",
      image_url: "https://www.themealdb.com/images/media/drink/uqxqsy1468876703.jpg",
    },
    {
      recipe_name: "Mac and Cheese",
      category: "American",
      ingredients: "Macaroni, cheddar cheese, butter, flour, milk, salt, pepper",
      instructions: "Cook macaroni. In a pan, make roux with butter and flour. Add milk and cheese to make sauce. Mix with pasta and bake until golden.",
      image_url: "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
    },
    {
      recipe_name: "Paneer Butter Masala",
      category: "Indian",
      ingredients: "Paneer cubes, butter, tomato puree, cream, ginger-garlic paste, garam masala",
      instructions: "Sauté ginger-garlic in butter, add tomato puree and spices. Simmer, then add cream and paneer cubes. Cook gently and serve with naan.",
      image_url: "https://www.themealdb.com/images/media/meals/vdwloy1711213796.jpg",
    },
    {
      recipe_name: "Chicken Curry",
      category: "Indian",
      ingredients: "Chicken, onion, tomato, ginger-garlic paste, garam masala, coriander, chili powder",
      instructions: "Sauté onions and ginger-garlic. Add tomatoes and spices. Add chicken, cover, and cook until tender. Garnish with coriander and serve with rice.",
      image_url: "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    },
    {
      recipe_name: "Spring Rolls",
      category: "Chinese",
      ingredients: "Cabbage, carrots, bell pepper, soy sauce, spring roll wrappers, oil",
      instructions: "Stir-fry vegetables with soy sauce. Place filling in wrappers, roll tightly, and fry until golden brown. Serve with chili sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/1529445434.jpg",
    },
    {
      recipe_name: "Omelette",
      category: "Breakfast",
      ingredients: "Eggs, milk, salt, pepper, onion, tomato, cheese, butter",
      instructions: "Whisk eggs with milk and seasoning. Pour on hot buttered pan, add veggies and cheese. Fold and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    },
    {
      recipe_name: "Caesar Salad",
      category: "Salad",
      ingredients: "Romaine lettuce, croutons, Parmesan, Caesar dressing, lemon juice, anchovies",
      instructions: "Toss lettuce with dressing and lemon juice. Add croutons and Parmesan. Serve chilled with anchovy fillets if desired.",
      image_url: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    },
    {
      recipe_name: "Masala Dosa",
      category: "Indian",
      ingredients: "Rice, urad dal, potatoes, onions, mustard seeds, curry leaves, chutney",
      instructions: "Ferment rice and dal batter overnight. Spread thin on hot tawa, fill with spiced potato mix, and fold. Serve with chutney and sambar.",
      image_url: "https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg",
    },
    {
      recipe_name: "Guacamole",
      category: "Mexican",
      ingredients: "Avocado, tomato, onion, cilantro, lime juice, salt, jalapeño",
      instructions: "Mash avocados and mix with chopped veggies, lime juice, and salt. Serve with nachos or tacos.",
      image_url: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    },
    {
      recipe_name: "Tiramisu",
      category: "Dessert",
      ingredients: "Ladyfingers, mascarpone, espresso, cocoa powder, sugar, eggs, rum",
      instructions: "Dip ladyfingers in espresso. Layer with mascarpone mixture made with eggs and sugar. Dust with cocoa. Chill for 4 hours before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/ytpstt1511386448.jpg",
    },
    {
      recipe_name: "Mutton Rogan Josh",
      category: "Indian",
      ingredients: "Mutton, onion, yogurt, garlic, ginger, Kashmiri chili, garam masala, ghee",
      instructions: "Brown onions in ghee, add ginger-garlic and spices. Add mutton and yogurt, cook on low flame until tender. Serve with rice or naan.",
      image_url: "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    },
    {
      recipe_name: "Pesto Pasta",
      category: "Italian",
      ingredients: "Basil, garlic, pine nuts, olive oil, Parmesan, spaghetti, salt",
      instructions: "Blend basil, garlic, and nuts with olive oil to make pesto. Toss cooked pasta with pesto and Parmesan. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    },
    {
      recipe_name: "French Toast",
      category: "Breakfast",
      ingredients: "Bread, eggs, milk, sugar, cinnamon, butter, syrup",
      instructions: "Whisk eggs, milk, and cinnamon. Dip bread slices and fry in butter until golden. Serve with syrup or powdered sugar.",
      image_url: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    },
    {
      recipe_name: "Clam Chowder",
      category: "Soup",
      ingredients: "Clams, potatoes, celery, onion, bacon, cream, butter, flour",
      instructions: "Cook bacon, add butter and veggies. Stir in flour, then milk and cream. Add clams and simmer. Serve warm with bread.",
      image_url: "https://www.themealdb.com/images/media/meals/rvtvuw1511190489.jpg",
    },
    {
      recipe_name: "Stuffed Bell Peppers",
      category: "Vegetarian",
      ingredients: "Bell peppers, rice, beans, tomato, onion, garlic, cheese, herbs",
      instructions: "Cut tops off peppers and stuff with cooked rice mixture. Bake until tender, sprinkle cheese, and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    },
    {
      recipe_name: "Shakshuka",
      category: "Middle Eastern",
      ingredients: "Eggs, tomatoes, onions, bell pepper, garlic, cumin, paprika, olive oil",
      instructions: "Cook onions and peppers in oil. Add tomatoes and spices, simmer. Make wells and crack eggs in. Cover and cook until eggs set. Serve with bread.",
      image_url: "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
    },
    {
      recipe_name: "Chocolate Mousse",
      category: "Dessert",
      ingredients: "Dark chocolate, eggs, sugar, cream, vanilla extract, salt",
      instructions: "Melt chocolate and cool. Whip egg whites and cream separately. Fold all together gently. Chill for 2 hours and serve cold.",
      image_url: "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
    },
    {
      recipe_name: "Chow Mein",
      category: "Chinese",
      ingredients: "Noodles, cabbage, carrots, soy sauce, garlic, ginger, sesame oil",
      instructions: "Boil noodles. Stir-fry garlic, ginger, and veggies. Add noodles and soy sauce, toss well. Serve with chili oil.",
      image_url: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    },
      {
      recipe_name: "Fish Tacos",
      category: "Mexican",
      ingredients: "White fish fillets, tortillas, cabbage, lime, mayonnaise, chili powder, garlic, cilantro",
      instructions: "Season fish with chili and garlic, grill until flaky. Mix lime and mayo for sauce. Fill tortillas with fish, cabbage, and sauce. Garnish with cilantro.",
      image_url: "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
    },
    {
      recipe_name: "Butter Chicken",
      category: "Indian",
      ingredients: "Chicken, butter, tomato puree, cream, garlic, ginger, garam masala, chili powder",
      instructions: "Marinate chicken in spices, grill, and cook in butter with tomato puree and cream. Simmer until thick and serve with naan.",
      image_url: "https://www.themealdb.com/images/media/meals/uwxusv1511554500.jpg",
    },
    {
      recipe_name: "Caprese Salad",
      category: "Italian",
      ingredients: "Tomatoes, mozzarella cheese, basil, olive oil, balsamic vinegar, salt, pepper",
      instructions: "Arrange sliced tomatoes and mozzarella alternately. Drizzle with olive oil and balsamic vinegar. Garnish with basil and serve fresh.",
      image_url: "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
    },
    {
      recipe_name: "Beef Stroganoff",
      category: "Russian",
      ingredients: "Beef strips, mushrooms, onions, sour cream, flour, butter, beef stock, mustard",
      instructions: "Sauté beef and set aside. Cook onions and mushrooms, add flour and stock, then beef and sour cream. Simmer gently and serve over noodles or rice.",
      image_url: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    },
    {
      recipe_name: "Shrimp Scampi",
      category: "Seafood",
      ingredients: "Shrimp, garlic, lemon juice, white wine, butter, parsley, spaghetti, olive oil",
      instructions: "Cook shrimp in butter and garlic. Add wine and lemon, simmer briefly. Toss with cooked pasta and parsley. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/xusqvw1511554429.jpg",
    },
    {
      recipe_name: "Chili Con Carne",
      category: "Mexican",
      ingredients: "Ground beef, kidney beans, tomatoes, onions, chili powder, cumin, garlic, peppers",
      instructions: "Brown beef, add onions and spices. Add beans and tomatoes, simmer for 40 minutes. Serve with rice or bread.",
      image_url: "https://www.themealdb.com/images/media/meals/uuqvwu1553038724.jpg",
    },
    {
      recipe_name: "Greek Salad",
      category: "Greek",
      ingredients: "Tomatoes, cucumber, olives, red onion, feta cheese, olive oil, oregano, lemon juice",
      instructions: "Chop veggies, mix in bowl, top with feta and olives. Drizzle olive oil and lemon juice. Sprinkle oregano and serve chilled.",
      image_url: "https://www.themealdb.com/images/media/meals/vtz3sw1511195147.jpg",
    },
    {
      recipe_name: "Falafel",
      category: "Middle Eastern",
      ingredients: "Chickpeas, garlic, parsley, onion, cumin, coriander, flour, oil",
      instructions: "Blend chickpeas and spices into dough, form balls, and deep fry until golden. Serve with pita and tahini sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/txutxu1511784264.jpg",
    },
    {
      recipe_name: "Lasagna",
      category: "Italian",
      ingredients: "Lasagna noodles, minced beef, tomato sauce, ricotta, mozzarella, Parmesan, herbs",
      instructions: "Layer cooked noodles with meat sauce and cheese. Repeat layers and bake until bubbly and golden. Rest before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    },
    {
      recipe_name: "Sushi Rolls",
      category: "Japanese",
      ingredients: "Sushi rice, nori sheets, cucumber, avocado, salmon, soy sauce, wasabi",
      instructions: "Place rice on nori, add fillings, roll tightly, and slice. Serve with soy sauce and wasabi.",
      image_url: "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
    },
    {
      recipe_name: "Eggplant Parmesan",
      category: "Italian",
      ingredients: "Eggplant, breadcrumbs, mozzarella, marinara sauce, Parmesan, basil, olive oil",
      instructions: "Coat eggplant in breadcrumbs, fry until golden. Layer with sauce and cheese, bake until bubbly. Garnish with basil.",
      image_url: "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    },
    {
      recipe_name: "Beef Burger",
      category: "American",
      ingredients: "Beef patty, burger bun, lettuce, tomato, cheese, onion, ketchup, mustard",
      instructions: "Grill beef patty, toast bun, assemble burger with vegetables and sauces. Serve with fries.",
      image_url: "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    },
    {
      recipe_name: "Chicken Caesar Wrap",
      category: "Snack",
      ingredients: "Grilled chicken, lettuce, Caesar dressing, tortilla wrap, Parmesan cheese",
      instructions: "Mix chicken and lettuce with dressing. Wrap tightly in tortilla and grill lightly. Slice and serve with sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    },
    {
      recipe_name: "Fried Calamari",
      category: "Seafood",
      ingredients: "Squid rings, flour, salt, pepper, lemon, oil, garlic aioli",
      instructions: "Coat squid in seasoned flour, fry until golden. Serve hot with lemon wedges and garlic aioli dip.",
      image_url: "https://www.themealdb.com/images/media/meals/ugdy2l1511177347.jpg",
    },
    {
      recipe_name: "Pancakes",
      category: "Breakfast",
      ingredients: "Flour, milk, eggs, sugar, baking powder, butter, syrup",
      instructions: "Whisk all ingredients to make batter. Pour on hot pan, cook until bubbles form, flip, and serve with syrup or fruits.",
      image_url: "https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg",
    },
    {
      recipe_name: "Gnocchi",
      category: "Italian",
      ingredients: "Potatoes, flour, egg, salt, butter, Parmesan, herbs",
      instructions: "Mash boiled potatoes, mix with flour and egg to make dough. Roll and cut into pieces, boil until they float. Toss in butter and herbs.",
      image_url: "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
    },
    {
      recipe_name: "Tom Yum Soup",
      category: "Thai",
      ingredients: "Shrimp, lemongrass, galangal, lime juice, chili, fish sauce, mushrooms",
      instructions: "Boil broth with lemongrass and galangal. Add shrimp, mushrooms, and seasonings. Simmer briefly and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    },
    {
      recipe_name: "Pavlova",
      category: "Dessert",
      ingredients: "Egg whites, sugar, cornstarch, vinegar, vanilla, cream, berries",
      instructions: "Whisk egg whites and sugar until stiff peaks. Bake low and slow. Top with whipped cream and fresh berries.",
      image_url: "https://www.themealdb.com/images/media/meals/ysxwuq1487330369.jpg",
    },
    {
      recipe_name: "Crispy Fried Chicken",
      category: "American",
      ingredients: "Chicken, flour, buttermilk, paprika, salt, pepper, oil",
      instructions: "Soak chicken in buttermilk, coat with seasoned flour, and deep fry until golden and crispy. Serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    },
    {
      recipe_name: "Vegetable Biryani",
      category: "Indian",
      ingredients: "Basmati rice, mixed vegetables, spices, yogurt, saffron, fried onions, ghee",
      instructions: "Cook vegetables with spices and yogurt. Layer with rice and saffron milk. Steam until fragrant and serve with raita.",
      image_url: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    },
    {
      recipe_name: "Chocolate Cake",
      category: "Dessert",
      ingredients: "Flour, cocoa powder, eggs, butter, sugar, milk, baking powder, frosting",
      instructions: "Mix dry and wet ingredients separately, then combine. Bake until done. Frost with chocolate icing and serve.",
      image_url: "https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg",
    },
    {
      recipe_name: "Margarita Pizza",
      category: "Italian",
      ingredients: "Pizza dough, tomato sauce, mozzarella, basil, olive oil, salt",
      instructions: "Spread sauce over dough, top with mozzarella and basil. Bake in hot oven until crust is golden and cheese melts.",
      image_url: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    },
    {
      recipe_name: "Thai Green Curry",
      category: "Thai",
      ingredients: "Chicken, green curry paste, coconut milk, eggplant, bamboo shoots, basil, fish sauce",
      instructions: "Fry curry paste, add coconut milk, chicken, and vegetables. Simmer until tender. Garnish with basil and serve with rice.",
      image_url: "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
    },
    {
      recipe_name: "Pulled Pork Sandwich",
      category: "American",
      ingredients: "Pork shoulder, BBQ sauce, burger buns, coleslaw, onion, spices",
      instructions: "Slow-cook pork with spices and BBQ sauce until tender. Shred and serve in buns with coleslaw.",
      image_url: "https://www.themealdb.com/images/media/meals/ttyrxr1511816755.jpg",
    },
    {
      recipe_name: "Greek Moussaka",
      category: "Greek",
      ingredients: "Eggplant, minced beef, tomato, onion, béchamel sauce, cheese, herbs",
      instructions: "Layer fried eggplant with meat sauce and béchamel. Bake until golden. Serve warm.",
      image_url: "https://www.themealdb.com/images/media/meals/ctg8gd1596536347.jpg",
    },
    {
      recipe_name: "Crème Brûlée",
      category: "Dessert",
      ingredients: "Egg yolks, sugar, cream, vanilla, caramelized sugar topping",
      instructions: "Whisk yolks with sugar, mix in cream and vanilla. Bake in ramekins, chill, then caramelize sugar on top with torch.",
      image_url: "https://www.themealdb.com/images/media/meals/uryqrs1511799717.jpg",
    },
    {
      recipe_name: "Ratatouille",
      category: "French",
      ingredients: "Eggplant, zucchini, tomato, bell pepper, onion, olive oil, herbs",
      instructions: "Layer thin slices of vegetables in a dish, drizzle with oil and herbs. Bake until tender and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    },
    {
      recipe_name: "Pad Thai",
      category: "Thai",
      ingredients: "Rice noodles, shrimp, egg, bean sprouts, tofu, peanuts, tamarind sauce, lime",
      instructions: "Stir-fry shrimp and tofu. Add noodles, sauce, and egg. Mix well and top with peanuts and lime wedges.",
      image_url: "https://www.themealdb.com/images/media/meals/uuqvwu1553038724.jpg",
    },
    {
      recipe_name: "Clam Chowder",
      category: "American",
      ingredients: "Clams, potatoes, onions, celery, bacon, heavy cream, butter, flour, thyme, bay leaf",
      instructions: "Cook bacon until crisp, remove and set aside. Sauté onions and celery in bacon fat, add flour to form roux. Pour in clam juice and cream, add potatoes and herbs. Simmer until potatoes are tender, then add clams. Heat gently and serve hot with bacon bits.",
      image_url: "https://www.themealdb.com/images/media/meals/rvtvuw1511190488.jpg",
    },
    {
      recipe_name: "Goulash",
      category: "Hungarian",
      ingredients: "Beef cubes, onions, garlic, paprika, tomatoes, bell peppers, beef broth, potatoes, carrots",
      instructions: "Sauté onions and garlic in oil, stir in paprika. Add beef cubes and brown. Add tomatoes, peppers, and broth. Simmer until beef is tender. Add potatoes and carrots, cook until soft, and serve hot.",
      image_url: "https://www.themealdb.com/images/media/meals/yyrrxr1511816289.jpg",
    },
    {
      recipe_name: "Eggs Benedict",
      category: "American",
      ingredients: "English muffins, eggs, Canadian bacon, butter, lemon juice, egg yolks, vinegar, cayenne pepper",
      instructions: "Prepare hollandaise by whisking yolks, lemon juice, and melted butter. Toast muffins and top with bacon. Poach eggs with vinegar. Assemble and drizzle with hollandaise sauce, sprinkle with cayenne.",
      image_url: "https://www.themealdb.com/images/media/meals/1550440197.jpg",
    },
    {
      recipe_name: "Pav Bhaji",
      category: "Indian",
      ingredients: "Potatoes, peas, cauliflower, tomatoes, butter, pav bhaji masala, onions, pav buns, lemon",
      instructions: "Boil and mash vegetables. Cook onions and tomatoes with spices and butter. Add mashed veggies and simmer until thick. Serve with butter-toasted pav and lemon wedges.",
      image_url: "https://www.themealdb.com/images/media/meals/tyvpxt1468315626.jpg",
    },
    {
      recipe_name: "Stuffed Bell Peppers",
      category: "Mediterranean",
      ingredients: "Bell peppers, rice, ground beef, onions, tomato sauce, garlic, herbs, cheese",
      instructions: "Cut tops off peppers, remove seeds. Mix beef, rice, onions, and sauce. Stuff peppers and bake until tender. Top with cheese and bake until melted.",
      image_url: "https://www.themealdb.com/images/media/meals/u55lbp1585564013.jpg",
    },
    {
      recipe_name: "Ceviche",
      category: "Peruvian",
      ingredients: "White fish, lime juice, red onion, cilantro, chili peppers, salt, sweet potato, corn",
      instructions: "Marinate fish in lime juice for 10–15 minutes. Add onions, cilantro, and chili. Mix gently and serve chilled with sweet potato and corn.",
      image_url: "https://www.themealdb.com/images/media/meals/1529442913.jpg",
    },
    {
      recipe_name: "Korean Bibimbap",
      category: "Korean",
      ingredients: "Rice, beef, spinach, carrots, bean sprouts, mushrooms, egg, gochujang sauce, sesame oil",
      instructions: "Prepare and season each vegetable separately. Cook beef with soy sauce and sesame oil. Arrange rice in bowl, top with vegetables, beef, and fried egg. Drizzle with gochujang and sesame oil before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg",
    },
    {
      recipe_name: "Chicken Fajitas",
      category: "Mexican",
      ingredients: "Chicken breast, bell peppers, onions, lime juice, cumin, chili powder, tortillas",
      instructions: "Marinate chicken with lime and spices. Grill with peppers and onions. Serve in warm tortillas with toppings like salsa and sour cream.",
      image_url: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    },
    {
      recipe_name: "Baklava",
      category: "Middle Eastern",
      ingredients: "Phyllo dough, walnuts, pistachios, butter, honey, sugar, cinnamon, lemon juice",
      instructions: "Layer phyllo sheets with butter and nuts. Bake until golden. Pour hot honey syrup over and let soak before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/wsqvys1468253248.jpg",
    },
    {
      recipe_name: "Moussaka",
      category: "Greek",
      ingredients: "Eggplant, minced lamb, onions, garlic, tomatoes, béchamel sauce, olive oil, cheese",
      instructions: "Fry eggplant slices. Prepare meat sauce with lamb and tomatoes. Layer eggplant, sauce, and béchamel. Bake until golden and bubbly.",
      image_url: "https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg",
    },
    {
      recipe_name: "Chicken Teriyaki Rice Bowl",
      category: "Japanese",
      ingredients: "Chicken thighs, soy sauce, mirin, sugar, garlic, rice, sesame seeds, scallions",
      instructions: "Cook chicken in teriyaki sauce until glazed. Serve over steamed rice topped with sesame seeds and scallions.",
      image_url: "https://www.themealdb.com/images/media/meals/4qr5ww1511784607.jpg",
    },
    {
      recipe_name: "Gnocchi with Pesto",
      category: "Italian",
      ingredients: "Gnocchi, basil, garlic, pine nuts, Parmesan cheese, olive oil, salt",
      instructions: "Boil gnocchi until they float. Blend pesto ingredients until smooth. Toss gnocchi in pesto and top with extra cheese.",
      image_url: "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
    },
    {
      recipe_name: "Peking Duck",
      category: "Chinese",
      ingredients: "Duck, honey, soy sauce, five-spice powder, hoisin sauce, scallions, pancakes",
      instructions: "Coat duck with honey glaze and roast until skin is crispy. Slice thinly and serve with pancakes, scallions, and hoisin sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    },
    {
      recipe_name: "Seafood Paella",
      category: "Spanish",
      ingredients: "Rice, shrimp, mussels, squid, saffron, bell peppers, peas, olive oil, paprika",
      instructions: "Sauté vegetables, add rice and saffron broth. Add seafood and cook until rice absorbs liquid and seafood is done. Garnish with lemon wedges.",
      image_url: "https://www.themealdb.com/images/media/meals/1520084413.jpg",
    },
    {
      recipe_name: "Chicken Shawarma",
      category: "Middle Eastern",
      ingredients: "Chicken thighs, yogurt, garlic, cumin, paprika, lemon juice, pita, tahini sauce",
      instructions: "Marinate chicken in yogurt and spices. Grill or roast until charred. Slice and serve in pita with veggies and tahini sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
    },
    {
      recipe_name: "Lamb Rogan Josh",
      category: "Indian",
      ingredients: "Lamb, onions, yogurt, garlic, ginger, tomato puree, garam masala, chili powder",
      instructions: "Brown lamb with onions and spices. Add yogurt and tomato puree, simmer until tender. Garnish with coriander and serve with rice.",
      image_url: "https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg",
    },
    {
      recipe_name: "Stuffed Cabbage Rolls",
      category: "Eastern European",
      ingredients: "Cabbage leaves, ground beef, rice, onions, tomato sauce, garlic, herbs",
      instructions: "Blanch cabbage leaves, fill with meat and rice mixture, roll tightly. Simmer in tomato sauce until tender.",
      image_url: "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    },
    {
      recipe_name: "Lobster Bisque",
      category: "French",
      ingredients: "Lobster, butter, onions, celery, brandy, tomato paste, cream, seafood stock, herbs",
      instructions: "Sauté vegetables in butter, add lobster shells and brandy. Stir in tomato paste and stock, simmer, then strain. Add cream and chunks of lobster before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg",
    },
    {
      recipe_name: "Beef Wellington",
      category: "British",
      ingredients: "Beef tenderloin, mushrooms, puff pastry, prosciutto, mustard, egg yolk, thyme",
      instructions: "Sear beef, coat with mustard. Wrap in prosciutto and mushroom duxelles, then in puff pastry. Bake until golden brown and serve sliced.",
      image_url: "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
    },
    {
      recipe_name: "Tiramisu",
      category: "Italian",
      ingredients: "Ladyfingers, espresso, mascarpone, eggs, sugar, cocoa powder, coffee liqueur",
      instructions: "Whisk yolks and sugar, fold in mascarpone. Dip ladyfingers in espresso and layer with cream mixture. Chill for hours and dust with cocoa powder before serving.",
      image_url: "https://www.themealdb.com/images/media/meals/xqrwyr1503066605.jpg",
    },
    {
      recipe_name: "Croissants",
      category: "French",
      ingredients: "Flour, butter, yeast, sugar, milk, salt, egg",
      instructions: "Prepare dough with layers of butter, fold and chill repeatedly to create laminations. Shape into crescents and bake until golden and flaky.",
      image_url: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
    },
    {
      recipe_name: "Pancit Canton",
      category: "Filipino",
      ingredients: "Egg noodles, chicken, shrimp, cabbage, carrots, soy sauce, oyster sauce, garlic",
      instructions: "Stir-fry meat and vegetables, add noodles and sauces, toss until evenly coated and noodles are tender. Serve with lemon wedges.",
      image_url: "https://www.themealdb.com/images/media/meals/rvtvuw1511190488.jpg",
    },
    {
      recipe_name: "Chicken Katsu",
      category: "Japanese",
      ingredients: "Chicken breast, panko breadcrumbs, eggs, flour, soy sauce, Worcestershire, ketchup",
      instructions: "Coat chicken in flour, egg, and panko. Fry until golden. Serve with tonkatsu sauce made from soy, Worcestershire, and ketchup.",
      image_url: "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    },
    {
      recipe_name: "Churros with Chocolate Sauce",
      category: "Spanish",
      ingredients: "Flour, butter, water, sugar, cinnamon, oil, dark chocolate, cream",
      instructions: "Make dough with flour and butter, pipe into hot oil, and fry until golden. Dust with cinnamon sugar and serve with melted chocolate sauce.",
      image_url: "https://www.themealdb.com/images/media/meals/1549542994.jpg",
    }
  ];



  async function seedData() {
    try {
      console.log("🌱 Seeding sample data...");

      for (const recipe of sampleRecipes) {
        await pool.query(
          `INSERT INTO recipes (recipe_name, category, ingredients, instructions, image_url)
          VALUES ($1, $2, $3, $4, $5)
          ON CONFLICT (recipe_name) DO NOTHING;`,
          [
            recipe.recipe_name,
            recipe.category,
            recipe.ingredients,
            recipe.instructions,
            recipe.image_url,
          ]
        );
      }

      console.log("✅ Sample data seeded successfully!");
    } catch (err) {
      console.error("❌ Error seeding data:", err);
    } finally {
      await pool.end();
    }
  }

  seedData();
